print("---------------------------------------------------")
day = input("Qual o dia do seu nascimento? -> ")
month = input("Qual o mês do seu nascimento? -> ")
year = input("Qual o ano do seu nascimento? -> ")
print("---------------------------------------------------")
print("Você nasceu em", day, "de", month, "de", year)
print("---------------------------------------------------")
print("Encerrando...")
print("---------------------------------------------------")
