print("---------------------------------------------------")
number1 = float(input("1º Número: "))
number2 = float(input("2º Número: "))
sum = (number1+number2)
print("---------------------------------------------------")
print("A soma dos números digitados é:", sum)
print("---------------------------------------------------")
print("Encerrando...")
print("---------------------------------------------------")
